// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var HttpServer = require("http-server");

var server = HttpServer.createServer({
      root: "files/"
    });

server.listen(8080);

server.close();

exports.server = server;
/* server Not a pure module */
